package com.example.expensetracker.persistence;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.example.expensetracker.model.Expense;
import com.example.expensetracker.repository.ExpenseRepository;
import java.math.BigDecimal;
import java.time.LocalDate;
import javax.sql.DataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

@SpringBootTest(properties = {
    "spring.datasource.url=jdbc:h2:mem:realm-primary;DB_CLOSE_DELAY=-1",
    "spring.datasource.username=sa",
    "spring.datasource.password=",
    "spring.datasource.driver-class-name=org.h2.Driver",
    "spring.datasource.hikari.minimum-idle=0",
    "demo.datasource.url=jdbc:h2:mem:realm-demo;DB_CLOSE_DELAY=-1",
    "demo.datasource.username=sa",
    "demo.datasource.password=",
    "demo.datasource.driver-class-name=org.h2.Driver",
    "demo.datasource.hikari.minimum-idle=0",
    "spring.jpa.database-platform=org.hibernate.dialect.H2Dialect",
    "spring.jpa.hibernate.ddl-auto=create-drop",
    "spring.flyway.enabled=false"
})
@ActiveProfiles("prod")
class DataRealmRoutingIntegrationTest {

    @Autowired
    private DataRealmExecutor realmExecutor;

    @Autowired
    private ExpenseRepository expenseRepository;

    @Autowired
    @Qualifier("primaryDataSource")
    private DataSource primaryDataSource;

    @Autowired
    @Qualifier("demoDataSource")
    private DataSource demoDataSource;

    private JdbcTemplate primaryJdbc;
    private JdbcTemplate demoJdbc;

    @BeforeEach
    void setUp() {
        primaryJdbc = new JdbcTemplate(primaryDataSource);
        demoJdbc = new JdbcTemplate(demoDataSource);
        primaryJdbc.update("delete from expense");
        demoJdbc.execute("drop table if exists expense");
        demoJdbc.execute("""
            create table expense (
                id bigint generated by default as identity primary key,
                description varchar(255),
                amount decimal(19, 2) not null,
                date date,
                category varchar(255),
                userid varchar(255),
                demo_session_id uuid,
                is_demo_seed boolean not null
            )
            """);
    }

    @Test
    void repositoryWritesOnlyToTheSelectedRealm() {
        realmExecutor.inRealm(DataRealm.PRIMARY, () -> expenseRepository.saveAndFlush(expense("primary")));
        realmExecutor.inRealm(DataRealm.DEMO, () -> expenseRepository.saveAndFlush(expense("demo")));

        assertThat(count(primaryJdbc)).isEqualTo(1);
        assertThat(count(demoJdbc)).isEqualTo(1);
        assertThat(DataRealmContext.current()).isEmpty();
    }

    @Test
    void contextIsClearedAfterFailureAndNestedRealmChangesAreRejected() {
        assertThatThrownBy(() -> realmExecutor.inRealm(DataRealm.DEMO, () -> {
            realmExecutor.inRealm(DataRealm.PRIMARY, () -> { });
        })).isInstanceOf(IllegalStateException.class);

        assertThat(DataRealmContext.current()).isEmpty();

        assertThatThrownBy(() -> realmExecutor.inRealm(DataRealm.DEMO, () -> {
            throw new IllegalArgumentException("boom");
        })).isInstanceOf(IllegalArgumentException.class);

        assertThat(DataRealmContext.current()).isEmpty();
    }

    private Expense expense(String description) {
        return Expense.builder()
            .description(description)
            .amount(BigDecimal.ONE)
            .date(LocalDate.of(2026, 8, 13))
            .category("Other")
            .userid("test-user")
            .build();
    }

    private long count(JdbcTemplate jdbcTemplate) {
        return jdbcTemplate.queryForObject("select count(*) from expense", Long.class);
    }
}
