name: Trigger auto deployment for ca-expensetracker-sea

on:
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-expensetracker-sea-AutoDeployTrigger-02d09508-69c2-4c78-95bf-5f88a9bb82d8.yml'
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CAEXPENSETRACKERSEA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAEXPENSETRACKERSEA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAEXPENSETRACKERSEA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.CAEXPENSETRACKERSEA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAEXPENSETRACKERSEA_REGISTRY_PASSWORD }}
          containerAppName: ca-expensetracker-sea
          resourceGroup: rg-expensetracker-sea
          imageToBuild: ghcr.io/${{ github.repository_owner }}/ca-expensetracker-sea:${{ github.sha }}
          targetPort: 8081
          ingress: external


