name: Trigger auto deployment for ca-expensetracker-sea-2

on:
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-expensetracker-sea-2-AutoDeployTrigger-65a65d55-1e56-420e-9ce3-ab41f0e895ae.yml'

  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
      packages: write      

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CAEXPENSETRACKERSEA2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAEXPENSETRACKERSEA2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAEXPENSETRACKERSEA2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile          
          registryUrl: ghcr.io
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.GITHUB_TOKEN }}
          containerAppName: ca-expensetracker-sea-2
          resourceGroup: rg-expensetracker-sea
          imageToBuild: ghcr.io/${{ github.repository_owner }}/ca-expensetracker-sea-2:${{ github.sha }}
          targetPort: 8081
          ingress: external


